// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWnj44NEJS_VfK-m9wzzJ4RL9DPcK9z9g',
    appId: '1:159512930700:web:be13712d89df5146c40ea9',
    messagingSenderId: '159512930700',
    projectId: 'dduff-e8a31',
    authDomain: 'dduff-e8a31.firebaseapp.com',
    databaseURL: 'https://dduff-e8a31-default-rtdb.firebaseio.com',
    storageBucket: 'dduff-e8a31.appspot.com',
    measurementId: 'G-4N8CRSGQR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFIIadl0sAlT-Cr5vEv3NgGcOdZJuqplc',
    appId: '1:159512930700:android:e0c9c80cef6d2b56c40ea9',
    messagingSenderId: '159512930700',
    projectId: 'dduff-e8a31',
    databaseURL: 'https://dduff-e8a31-default-rtdb.firebaseio.com',
    storageBucket: 'dduff-e8a31.appspot.com',
  );
}
